{{ if eq .Values.secretProvider "aws" }}
{{ if .Values.awsSecretManagerSecretArn }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: k8s-informer-{{ .Values.secretProvider }}-{{ .Values.instance.name }}
  annotations:
    helm.sh/hook: pre-install
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ .Values.awsSecretManagerSecretArn }}
          jmesPath: 
            - path: username
              objectAlias: .user
            - path: password
              objectAlias: .password
            {{ if .Values.connectionsDiscovery.prometheusBasicAuth }}
            - path: prometheus_user
              objectAlias: prometheus_user
            - path: prometheus_password
              objectAlias: prometheus_password
            {{ end }}
            {{ if and .Values.connectionsDiscovery .Values.connectionsDiscovery.method (eq .Values.connectionsDiscovery.method "servicenow")}}
            {{ if not (eq .Values.connectionsDiscovery.tls.mode "None") }}
            - path: server_key
              objectAlias: server_key
            - path: server_cert
              objectAlias: server_cert
            {{ if or (eq .Values.connectionsDiscovery.tls.mode "mTLS") (eq .Values.connectionsDiscovery.tls.mode "VerifyClientCertificate") }}
            - path: client_key
              objectAlias: client_key
            - path: client_cert
              objectAlias: client_cert
            {{ end }}
            {{ if eq .Values.connectionsDiscovery.tls.customCa true }}
            {{ if or (eq .Values.connectionsDiscovery.tls.mode "mTLS") (eq .Values.connectionsDiscovery.tls.mode "VerifyServerCertifcate") (eq .Values.connectionsDiscovery.tls.mode "VerifyClientCertificate")}}
            - path: ca_cert
              objectAlias: ca_cert
            {{ end }}
            {{ end }}
            {{ end }}
            {{ end }}
{{ else }}
  {{fail "\n\nError: Please provide AWS secret ARN by --set awsSecretManagerSecretArn=<ARN>\n\n"}}
{{ end }}
{{ end }}
