{{ if eq .Values.secretProvider "google" }}
{{ if .Values.googleSecrets.projectId }}
{{ if .Values.googleSecrets.userSecret }}
{{ if .Values.googleSecrets.passwordSecret }}
{{ if .Values.googleSecrets.userSecretVersion }}
{{ if .Values.googleSecrets.passwordSecretVersion }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: k8s-informer-{{ .Values.secretProvider }}-{{ .Values.instance.name }}
  annotations:
    helm.sh/hook: pre-install
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.userSecret}}/versions/{{ .Values.googleSecrets.userSecretVersion }}"
        path: ".user"
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.passwordSecret}}/versions/{{ .Values.googleSecrets.passwordSecretVersion }}"
        path: ".password"
      {{ if .Values.googleSecrets.oauthClientIdSecret }}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.oauthClientIdSecret}}/versions/{{ .Values.googleSecrets.oauthClientIdVersion }}"
        path: ".client_id"
      {{ end }}
      {{ if .Values.googleSecrets.oauthClientSecret }}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.oauthClientSecret}}/versions/{{ .Values.googleSecrets.oauthClientSecretVersion }}"
        path: ".client_secret"
      {{ end }}
      {{ if .Values.googleSecrets.proxyUserSecret }}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.proxyUserSecret}}/versions/{{ .Values.googleSecrets.proxyUserSecretVersion }}"
        path: ".proxyUser"
      {{ end }}
      {{ if .Values.googleSecrets.proxyPasswordSecret }}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.proxyPasswordSecret}}/versions/{{ .Values.googleSecrets.proxyPasswordSecretVersion }}"
        path: ".proxyPassword"
      {{ end }}
      {{ if .Values.googleSecrets.prometheusUserSecret}}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.prometheusUserSecret}}/versions/{{ .Values.googleSecrets.prometheusUserSecretVersion }}"
        path: "prometheus_user"
      {{ end }}
      {{ if .Values.googleSecrets.prometheusPasswordSecret}}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.prometheusPasswordSecret}}/versions/{{ .Values.googleSecrets.prometheusPasswordSecretVersion }}"
        path: "prometheus_password"
      {{ end }}
      {{ if and .Values.connectionsDiscovery .Values.connectionsDiscovery.method (eq .Values.connectionsDiscovery.method "servicenow") (not (eq .Values.connectionsDiscovery.tls.mode "None")) }}
      {{ if .Values.googleSecrets.serverKeySecret}}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.serverKeySecret}}/versions/{{ .Values.googleSecrets.prometheusPasswordSecretVersion }}"
        path: "server_key"
      {{ end }}
      {{ if .Values.googleSecrets.serverCertificateSecret}}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.serverCertificateSecret}}/versions/{{ .Values.googleSecrets.prometheusPasswordSecretVersion }}"
        path: "server_cert"
      {{ end }}
      {{ if .Values.googleSecrets.clientKeySecret}}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.clientKeySecret}}/versions/{{ .Values.googleSecrets.prometheusPasswordSecretVersion }}"
        path: "client_key"
      {{ end }}
      {{ if .Values.googleSecrets.clientCertificateSecret}}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.clientCertificateSecret}}/versions/{{ .Values.googleSecrets.prometheusPasswordSecretVersion }}"
        path: "client_cert"
      {{ end }}
      {{ if .Values.googleSecrets.customCaCertificateSecret}}
      - resourceName: "projects/{{ .Values.googleSecrets.projectId }}/secrets/{{ .Values.googleSecrets.customCaCertificateSecret}}/versions/{{ .Values.googleSecrets.prometheusPasswordSecretVersion }}"
        path: "ca_cert"
      {{ end }}
      {{ end }}

{{ else }}
  {{fail "\n\nError: Please provide the ServiceNow instance password secret version by --set googleSecrets.passwordSecretVersion=<SECRET_VERSION>\n\n"}}
{{ end }}
{{ else }}
  {{fail "\n\nError: Please provide the ServiceNow instance user secret version by --set googleSecrets.userSecretVersion=<SECRET_VERSION>\n\n"}}
{{ end }}
{{ else }}
  {{fail "\n\nError: Please provide the ServiceNow instance password secret name by --set googleSecrets.passwordSecret=<SECRET_NAME>\n\n"}}
{{ end }}
{{ else }}
  {{fail "\n\nError: Please provide the ServiceNow instance user secret name by --set googleSecrets.userSecret=<SECRET_NAME>\n\n"}}
{{ end }}
{{ else }}
  {{fail "\n\nError: Please provide Google project ID by --set googleSecrets.projectId=<PROJECT_ID>\n\n"}}
{{ end }}
{{ end }}