{{ if .Values.instanceCredentials.username }}
apiVersion: v1
kind: Secret  
metadata:
  name: {{ .Values.instanceCredSecretName }}-{{ .Values.instance.name }}
  labels:
    app: k8s_informer-{{ .Values.instance.name }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/hook: pre-install
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  .user: {{ .Values.instanceCredentials.username | b64enc | quote }}
  .password: {{ required "Use --set instanceCredentials.password=<PASSWORD> to provide the instance password" .Values.instanceCredentials.password | b64enc | quote }}
  {{ if .Values.instanceCredentials.clientId }}
  .client_id: {{ .Values.instanceCredentials.clientId | b64enc | quote }}
  .client_secret: {{ required "Use --set instanceCredentials.clientSecret=<CLIENT_SECRET> to provide the client secret"  .Values.instanceCredentials.clientSecret | b64enc | quote }}
  {{ end }}
{{ end }}
