apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}-{{ .Values.instance.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{ if .Values.awsSecretManagerRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.awsSecretManagerRoleArn }}
{{ end }}
  {{ if and (eq .Values.secretProvider "azure") (eq .Values.azureVault.vaultType "rbac") }}
    azure.workload.identity/client-id: {{ .Values.azureVault.userAssignedIdentityId }}
{{ end }}
automountServiceAccountToken: false
---
{{ if not .Values.customClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole }}-{{ .Release.Namespace }}-{{ .Values.instance.name }}
  labels:
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
      - services
      - replicationcontrollers
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - images
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - user.openshift.io
    resources:
      - users
      - groups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - project.openshift.io
    resources:
      - projects
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - image.openshift.io
    resources:
      - images
      - imagestreams
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch

{{ if .Values.kubevirt.enabled }}
{{- range .Values.kubevirt.resources | fromYamlArray }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 6 }}
    resources: {{ required "resources not provided in kubervirt.resources" .resources | toYaml | nindent 6 }}
    verbs:
      - get
      - list
      - watch
{{- end }}
{{ end }}
{{ if .Values.additionalResources.resources }}
{{- range .Values.additionalResources.resources | fromYamlArray }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 6 }}
    resources: {{ required "resources not provided in additionalResources.resources" .resources | toYaml | nindent 6 }}
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- end }}
{{ if .Values.additionalResources.resources_oob }}
{{- range .Values.additionalResources.resources_oob | fromYamlArray }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 6 }}
    resources: {{ required "resources not provided in additionalResources.resources_oob" .resources | toYaml | nindent 6 }}
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- end }}
---
{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount }}-{{ .Values.clusterRole }}--{{ .Release.Namespace }}-{{ .Values.instance.name }}
  labels:
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{ if .Values.customClusterRole }}
  name: {{ .Values.customClusterRole }}
{{ else }}
  name: {{ .Values.clusterRole }}-{{ .Release.Namespace }}-{{ .Values.instance.name }}
{{ end }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount }}-{{ .Values.instance.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.role }}-{{ .Release.Namespace }}-{{ .Values.instance.name }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
{{ if eq .Values.selfPatchingAllowed true }}
  - apiGroups:
      - apps
    resources:
      - deployments
      {{ if and .Values.connectionsDiscovery .Values.connectionsDiscovery.method (eq .Values.connectionsDiscovery.method "servicenow")}}
      - daemonsets
      {{ end }}
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
{{ end }}
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - k8s-informer-additional-resources-{{ .Values.instance.name }}
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount }}-{{ .Values.role }}--{{ .Release.Namespace }}-{{ .Values.instance.name }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount }}-{{ .Values.instance.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.role }}-{{ .Release.Namespace }}-{{ .Values.instance.name }}
  apiGroup: rbac.authorization.k8s.io
{{ if and .Values.connectionsDiscovery .Values.connectionsDiscovery.method (eq .Values.connectionsDiscovery.method "servicenow")}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.connectionsDiscovery.daemonsetServiceAccount }}-{{ .Values.instance.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{ if .Values.awsSecretManagerRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.awsSecretManagerRoleArn }}
    {{ end }}
    {{ if and (eq .Values.secretProvider "azure") (eq .Values.azureVault.vaultType "rbac") }}
    azure.workload.identity/client-id: {{ .Values.azureVault.userAssignedIdentityId }}
    {{ end }}
automountServiceAccountToken: false
{{ end }}
