{{ if and .Values.connectionsDiscovery .Values.connectionsDiscovery.method (or (eq .Values.connectionsDiscovery.method "servicenow") (eq .Values.connectionsDiscovery.method "cilium"))}}
apiVersion: v1
kind: Service
metadata:
  name: k8s-informer-{{ .Values.instance.name }}-svc
  labels:
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: k8s-informer-{{ .Values.instance.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.connectionsDiscovery.httpServerPort }}
      targetPort: {{ .Values.connectionsDiscovery.httpServerPort }}
{{ end }}